import Head from "next/head";
import Banner from "../components/Banner";
import Introduction from "../components/Sections/Introduction";
import ProjectSection from "../components/Sections/Project";

export default function Home() {
  return (
    <div className="home-page">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <Introduction />
      <ProjectSection />

      {/* <ProjectSection /> */}
    </div>
  );
}
