import Head from "next/head";
import Image from "next/image";
import { gsap } from "gsap";
import ScrollTrigger from "gsap/dist/ScrollTrigger";

import styles from "../styles/Home.module.css";
import { useEffect, useRef } from "react";
import Banner from "../components/Banner";
import Introduction from "../components/Sections/Introduction";

export default function Home() {
  return (
    <div className="home-page">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <Introduction />
    </div>
  );
}
