import Head from "next/head";
import Banner from "../../components/Banner";
import Introduction from "../../components/Sections/Introduction";
import ProjectSection from "../../components/Sections/Project";
import Navbar from "../../components/Navbar";

export default function Home() {
  return (
    <div className="home-page">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <Navbar />
      {/* <Introduction /> */}
      {/* <ProjectSection /> */}

      {/* <ProjectSection /> */}
    </div>
  );
}

export async function getStaticProps() {
  return {
    props: {
      id: "home",
    },
  };
}
